use crate::types::{
    EphemeralKeyPair,  
    StaticKeyPair, 
    StealthInput
};
use rand_core::OsRng;
use x25519_dalek::{
    PublicKey as X25519PublicKey, 
    StaticSecret as X25519StaticSecret,
};

fn generate_x25519_keypair() -> (X25519StaticSecret, X25519PublicKey) {
    let private_key = X25519StaticSecret::random_from_rng(&mut OsRng);
    let public_key = X25519PublicKey::from(&private_key);
    
    (private_key, public_key)
}

/// Ephemeral keypair is a per message key that is used for encryption, and 
/// travels in the envelope. 
/// It is generated by the sender for each message, and discarded after use.
pub fn generate_ephemeral_keypair() -> EphemeralKeyPair {
    let (secret, public) = generate_x25519_keypair();
    
    EphemeralKeyPair {
        secret: X25519StaticSecret::from(secret.to_bytes()),
        public: X25519PublicKey::from(public.to_bytes()),
    }
}

/// Static keypair is a per correspondant key that is used for multiple 
/// encryptions, and never travels. 
/// It is generated by the recipient and shared with the sender out of scope of 
/// the protocol. It is used to compute the shared secret for identification and to derive the tag and binding keys.
pub fn generate_static_keypair() -> StaticKeyPair {
    let (sk_b, pk_b) = generate_x25519_keypair();
    
    StaticKeyPair {
        sk_b: X25519StaticSecret::from(sk_b.to_bytes()),
        pk_b: X25519PublicKey::from(pk_b.to_bytes()),
    }
}

/// Compute the stealth input via X25519 Diffie-Hellman.
///
/// Called by the sender as:
///   compute_stealth_input(&ephemeral_secret, &recipient_static_public)
///
/// Called by the recipient as:
///   compute_stealth_input(&static_secret, &sender_ephemeral_public)
///
/// Both calls produce identical output — this is the DH guarantee.
/// The result is used as input to key derivation in kdf.rs.
/// It is never stored beyond that derivation.
pub fn compute_stealth_input(secret: &X25519StaticSecret, public: &X25519PublicKey) -> StealthInput {
    StealthInput(secret.diffie_hellman(public).to_bytes())
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_compute_stealth_input() {
        println!("Testing compute_stealth_input consistency sender == recipient generation...");
        
        let recipient_static = generate_static_keypair();
        let sender_ephemeral = generate_ephemeral_keypair();

        let sender_stealth_input = compute_stealth_input(&sender_ephemeral.secret, &recipient_static.pk_b);
        let recipient_stealth_input = compute_stealth_input(&recipient_static.sk_b, &sender_ephemeral.public);

        assert_eq!(sender_stealth_input.0, recipient_stealth_input.0);
    }
}