use crate::types::{EphemeralKeyPair, PublicKey, StaticKeyPair, StaticSecret, StealthInput};
use x25519_dalek::{
    PublicKey as X25519PublicKey, 
    StaticSecret as X25519StaticSecret
};
use rand_core::OsRng;

fn generate_x25519_keypair() -> (X25519StaticSecret, X25519PublicKey) {
    let private_key = X25519StaticSecret::new(&mut OsRng);
    let public_key = X25519PublicKey::from(&private_key);
    (private_key, public_key)
}

/// Ephemeral keypair is a per message key that is used for encryption, and 
/// travels in the envelope. 
/// It is generated by the sender for each message, and discarded after use.
pub fn generate_ephemeral_keypair() -> EphemeralKeyPair {
    let (secret, public) = generate_x25519_keypair();
    
    EphemeralKeyPair {
        secret: StaticSecret(secret.to_bytes()),
        public: PublicKey(public.to_bytes()),
    }
}

/// Static keypair is a per correspondant key that is used for multiple 
/// encryptions, and never travels. 
/// It is generated by the recipient and shared with the sender out of scope of 
/// the protocol. It is used to compute the shared secret for identification and to derive the tag and binding keys.
pub fn generate_static_keypair() -> StaticKeyPair {
    let (sk_b, pk_b) = generate_x25519_keypair();
    
    StaticKeyPair {
        sk_b: StaticSecret(sk_b.to_bytes()),
        pk_b: PublicKey(pk_b.to_bytes()),
    }
}

/// Compute the stealth input via X25519 Diffie-Hellman.
///
/// Called by the sender as:
///   compute_stealth_input(&ephemeral_secret, &recipient_static_public)
///
/// Called by the recipient as:
///   compute_stealth_input(&static_secret, &sender_ephemeral_public)
///
/// Both calls produce identical output — this is the DH guarantee.
/// The result is used as input to key derivation in kdf.rs.
/// It is never stored beyond that derivation.
pub fn compute_stealth_input(secret: &SecretKey, public: &PublicKey) -> StealthInput {
    let dh_secret = DhSecret::from(secret.0);
    let dh_public = DhPublic::from(public.0);
    
    StealthInput(dh_secret.diffie_hellman(&dh_public).to_bytes())
}