[package]
name = "crypto-primitives"
version = "0.1.0"
edition = "2024"

[dependencies]
getrandom = "0.4.2"
rand = { version = "0.10.1", features = ["sys_rng"] }
rand_core = { version = "0.6", features = ["getrandom"] } 
# for rand_core::OsRng. TODO: find alternative
serde = "1.0.228"
tfhe = { version = "1.6.1", features = ["boolean", "integer", "shortint"] }
thiserror = "2.0.18"
x25519-dalek = { version = "2.0.1", features = ["static_secrets"] }
zeroize = "1.8.2"
